version: "3"

services:
  postgres:
    image: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data:/data/postgres
    ports:
      - "5432:5432"
